APP_NAME="NetForge"
DNS_SERVERS="1.1.1.1 1.0.0.1 8.8.8.8"
DISABLE_SSHD=true
DISABLE_FILE_SHARE=true
HIGH_PERFORMANCE_POWER=false
RESPECT_VPN=true
CAPTIVE_PORTAL_DNS="1.1.1.1 8.8.8.8"
CAPTIVE_AUTO_RESTORE_SECONDS=600
