APP_NAME="NetForge"
DNS_SERVERS="1.1.1.1 1.0.0.1 8.8.8.8"
ETHERNET_METRIC=5
WIFI_METRIC_ALONE=10
WIFI_METRIC_WITH_ETH=50
LOCK_SECONDS=90
MAX_LOG_LINES=2000
DISABLE_SSHD=true
DISABLE_FILE_SHARE=true
DISABLE_AWDL=false
HIGH_PERFORMANCE_POWER=true
INSTALL_DIR="/opt/netforge"
RESPECT_VPN=true
CAPTIVE_PORTAL_DNS="1.1.1.1 8.8.8.8"
CAPTIVE_AUTO_RESTORE_SECONDS=900
